apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress/ui-ingress.yaml
  - ingress/grafana-ingress.yaml
  - ingress/prometheus-ingress.yaml

patchesStrategicMerge:
  - patches/bubble-sort-image.yaml
  - patches/merge-sort-image.yaml
  - patches/ui-image.yaml
