global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'bubble-sort'
    static_configs:
      - targets: ['bubble-sort:8080']
        labels:
          algorithm: 'bubble'
  
  - job_name: 'merge-sort'
    static_configs:
      - targets: ['merge-sort:8080']
        labels:
          algorithm: 'merge'
          
