apiVersion: apps/v1
kind: Deployment
metadata:
  name: bubble-sort
spec:
  template:
    spec:
      containers:
      - name: bubble-sort
        image: bubble-sort:latest
        imagePullPolicy: Never
